### ISSUE TITLE
Cannot find module 'yt-list'

### ISSUE THREAD

**Issue by gsellitto** [mlomboglia/alexa-skill-heytube#5]
Hi, when i try to execute i've got the error:
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module 'yt-list'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module 'yt-list'",
        "Require stack:",
        "- /var/task/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:100:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:140:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:30)",
        "    at Module._compile (internal/modules/cjs/loader.js:999:30)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)",
        "    at Module.load (internal/modules/cjs/loader.js:863:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:708:14)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}

How to solve?
Thank you.

**Comment by gsellitto** [comment]
Ok, solved. 
The problem was that i executed npm -i ... in the root folder and not in lambda folder.
Bye.
