### ISSUE TITLE
 Error: This utterance did not resolve to any intent in your skill when trying to speak with the skill(ask dialog)

### ISSUE THREAD

**Issue by justinh998** [mlomboglia/alexa-skill-heytube#7]
hello , i cloned the code from git and then kept the code from mulitple audio , then deleted the skill ids so the skill created new ones (this created an error ,. something else i didn't change . I wanted to translate the skill for me into German , but I wanted to try first , how the basic skill works . I can also compile it. I can also enter ask dialog , but as soon as I try to start the skill with : Alexa open hey tube I get after a short time the following error:
`[Error]: Failed to simulate skill. Error: This utterance did not resolve to any intent in your skill. Please invoke your skill and try again with a different utterance or update your interaction model to include this utterance before testing again.
Uncaught:
RetriableServiceError: Failed to simulate skill. Error: This utterance did not resolve to any intent in your skill. Please invoke your skill and try again with a different utterance or update your interaction model to include this utterance before testing again.
    at InteractiveMode.evaluateUtterance (C:\Users\Justi\AppData\Roaming\npm\node_modules\ask-cli\dist\lib\controllers\dialog-controller\index.js:59:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at InteractiveMode.getSkillSimulationResult (C:\Users\Justi\AppData\Roaming\npm\node_modules\ask-cli\dist\lib\controllers\skill-simulation-controller\index.js:109:23) {
  payload: {
    id: '81bd3758-8677-4819-ae8d-8fd7abd31d8d',
    status: 'FAILED',
    result: { alexaExecutionInfo: [Object], error: [Object] }
  }
I just don't know what to do anymore.`

**Comment by justinh998** [comment]
I just checked my computer, it doesn't seem to be a problem, the open world skill works.
